version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g serverless
      - npm install
      - apk update 
      - apk add docker
      - systemctl start docker
      - systemctl enable docker

  build:
    commands:
      - echo "Running database migrations..."
      - echo "Running tests..."
      - npm run test
      - echo "Pulling mongodb image..."
      - docker pull mongo
      - echo "running mongodb image..."
      - docker run -d --name mongodb-test -p 27017:27017 mongo
      - echo "running Integration tests..."
      - npm run integration-test
      - echo "stopping mongodb containers..."
      - docker stop mongodb-test
      - docker rm mongodb-test
      - echo "Packaging and deploying the serverless application..."
      - serverless deploy --stage $ENVIRONMENT

cache:
  paths:
    - node_modules

    