version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g serverless
      - npm install
  build:
    commands:
      - echo "Running database migrations..."
  test:
    commands:
      - echo "Running tests..."
      - npm run test
  post_build:
    commands:
      - echo "Packaging and deploying the serverless application..."
      - serverless package
      - serverless deploy --stage $ENVIRONMENT      

cache:
  paths:
    - node_modules