version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g serverless
      - npm install

  build:
    commands:
      - echo "Running database migrations..."
      - echo "Running tests..."
      - npm run test
      - echo "Packaging and deploying the serverless application..."
      - serverless deploy --stage $ENVIRONMENT

cache:
  paths:
    - node_modules